apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  selector:
    matchLabels:
      app: organic
  template:
    metadata:
      labels:
        app: organic
    spec:
      containers:
      - name: example-cont
        image: muralisocial123/organic-app-web:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "128Mi" 
            cpu: "50m" 
        ports:
        - containerPort: 5656
--- 
apiVersion: v1 
kind: Service
metadata:
  name: web-app-deployment-svc
spec:
  selector:
    app: organic
  ports:
  - port: 5657
    targetPort: 5656
  type: LoadBalancer 
--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
    

  